### ISSUE TITLE
Can this tool rotate the map by any Angle and then merge it?

### ISSUE THREAD

**Issue by prank0011** [RestoreMonarchy/UnturnedMapMergeTool#1]
Also, can this tool also merge objects placed using Devkit?

**Comment by RestoreMonarchy** [comment]
I don't have a good idea how devkit works. If it saves data to the Objects.dat file as well as legacy map editor then it will work. It doesn't merge any data from level.hierarchy tho.
At the moment the program doesn't allow rotation of the maps, but it can be pretty easily added.

**Comment by prank0011** [comment]
I have tried to edit Level. hierarchy file with Notepad ++, which can edit information such as volume, position and zoom, and the result is very good.
Maybe I can use Excle to edit it myself.

**Comment by RestoreMonarchy** [comment]
While i was working on this tool I saw in Unturned source code that objects.dat file is always loaded for every map, even the ones made in devkit. You can try running this tool on your devkit map and see if it will work. I think it will

**Comment by prank0011** [comment]
I will try it sometime. Thank you for your reply.
